#include "gimbal_control.h"
#include "gimbal_proto_rs3.h"
#include <assert.h>
#include <string.h>
#include "rs3_pose_fixtures.h"

static unsigned received;
static void frame(void *context, const uint8_t *p, size_t n)
{ (void)context; assert(rs3_valid(p,n)); ++received; }
int main(void)
{
    /* Independent exact capture, not generated by this encoder. */
    const uint8_t neutral[]={0x55,0x16,0x04,0xfc,0x02,0x04,0x4b,0x17,0x40,0x04,0x01,0,4,0,4,0,4,0,0,2,0x1b,0x3a};
    uint8_t bytes[RS3_FRAME_MAX];
    assert(rs3_stick(bytes,sizeof(bytes),0x174b,0,0)==sizeof(neutral));
    assert(!memcmp(bytes,neutral,sizeof(neutral)) && rs3_valid(neutral,sizeof(neutral)));
    const uint8_t tilt[]={0x55,0x16,0x04,0xfc,0x02,0x04,0x57,0x17,0x40,0x04,0x01,0x7c,5,0,4,0,4,0,0,2,0x48,0xdf};
    assert(rs3_stick(bytes,sizeof(bytes),0x1757,0,380)==sizeof(tilt) && !memcmp(bytes,tilt,sizeof(tilt)));
    assert(!rs3_stick(bytes,21,1,0,0) && !rs3_stick(bytes,sizeof(bytes),1,401,0));
    assert(!rs3_frame(bytes,sizeof(bytes),1,4,0x40,4,1,NULL,1));
    assert(rs3_center(bytes,sizeof(bytes),0xffff)==15 && rs3_valid(bytes,15));
    assert(bytes[6]==255 && bytes[7]==255 && bytes[10]==0x4c && bytes[11]==0xfe && bytes[12]==1);
    rs3_stream_t stream={0};
    for (unsigned i=0;i<sizeof(neutral);++i) rs3_stream_feed(&stream,neutral+i,1,frame,NULL);
    assert(received==1);
    uint8_t bad[sizeof(neutral)]; memcpy(bad,neutral,sizeof(bad)); bad[18]^=1;
    rs3_stream_feed(&stream,bad,sizeof(bad),frame,NULL);
    rs3_stream_feed(&stream,neutral,sizeof(neutral),frame,NULL);
    rs3_stream_feed(&stream,neutral,sizeof(neutral),frame,NULL); assert(received==3);
    for (unsigned i=0;i<sizeof(neutral);++i) { memcpy(bad,neutral,sizeof(bad)); bad[i]^=1; assert(!rs3_valid(bad,sizeof(bad))); }
    uint8_t payload[21]={0}; payload[20]=88;
    size_t n=rs3_frame(bytes,sizeof(bytes),1,2,0,0x0d,2,payload,sizeof(payload)); bytes[4]=0xe5;
    /* Altering sender without recomputing CRC cannot publish battery. */
    uint8_t battery; assert(!rs3_battery(bytes,n,&battery));
    /* Independently generated by the pinned Python DUML reference. */
    const uint8_t battery88[]={0x55,0x22,0x04,0xea,0xe5,0x02,0x34,0x12,0,0x0d,2,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0x58,0x67,0x3a};
    assert(rs3_battery(battery88,sizeof(battery88),&battery) && battery==88);
    /* Valid frame CRC is insufficient: reject ambiguous/wrong-width TLVs,
     * missing axes, wrong endpoint/command, and never partially publish. */
    rs3_pose_raw_t pose;
    assert(rs3_pose_raw(pose_captured,sizeof(pose_captured),&pose));
    assert(pose.pan==-2 && pose.tilt==-123 && pose.roll==2);
    assert(rs3_pose_raw(pose_extremes,sizeof(pose_extremes),&pose));
    assert(pose.pan==0 && pose.tilt==INT16_MIN && pose.roll==INT16_MAX);
    assert(rs3_pose_raw(pose_reordered,sizeof(pose_reordered),&pose));
    assert(pose.pan==INT16_MAX && pose.tilt==INT16_MIN && pose.roll==0);
    const struct { const uint8_t *data; size_t size; } invalid_pose[]={
        {pose_wrong_width,sizeof(pose_wrong_width)}, {pose_missing,sizeof(pose_missing)},
        {pose_duplicate,sizeof(pose_duplicate)}, {pose_trailing,sizeof(pose_trailing)},
        {pose_truncated,sizeof(pose_truncated)}, {pose_wrong_header,sizeof(pose_wrong_header)},
        {pose_wrong_id,sizeof(pose_wrong_id)}, {pose_wrong_sender,sizeof(pose_wrong_sender)},
        {pose_wrong_receiver,sizeof(pose_wrong_receiver)}, {pose_empty,sizeof(pose_empty)},
    };
    const rs3_pose_raw_t sentinel={.pan=11,.tilt=22,.roll=33};
    for (size_t i=0;i<sizeof(invalid_pose)/sizeof(invalid_pose[0]);++i) {
        assert(rs3_valid(invalid_pose[i].data,invalid_pose[i].size));
        pose=sentinel;
        assert(!rs3_pose_raw(invalid_pose[i].data,invalid_pose[i].size,&pose));
        assert(pose.pan==11 && pose.tilt==22 && pose.roll==33);
    }
    for (size_t size=0;size<sizeof(pose_captured);++size) {
        pose=sentinel;
        assert(!rs3_pose_raw(pose_captured,size,&pose) && pose.pan==11 && pose.tilt==22 && pose.roll==33);
    }
    assert(!rs3_pose_raw(NULL,0,&pose) && !rs3_pose_raw(pose_captured,sizeof(pose_captured),NULL));
    for (size_t split=0;split<=sizeof(neutral);++split) {
        stream=(rs3_stream_t){0}; unsigned before=received;
        rs3_stream_feed(&stream,neutral,split,frame,NULL);
        rs3_stream_feed(&stream,neutral+split,sizeof(neutral)-split,frame,NULL);
        assert(received==before+1 && !stream.used);
    }
    uint8_t joined[sizeof(neutral)*2]; memcpy(joined,neutral,sizeof(neutral)); memcpy(joined+sizeof(neutral),neutral,sizeof(neutral));
    unsigned before=received; rs3_stream_feed(&stream,joined,sizeof(joined),frame,NULL); assert(received==before+2);
    /* Oversize header and arbitrary garbage must not prevent valid recovery. */
    const uint8_t garbage[]={0xff,0x55,0xff,7,0,0x55,0,4,0};
    rs3_stream_feed(&stream,garbage,sizeof(garbage),frame,NULL);
    before=received; rs3_stream_feed(&stream,neutral,sizeof(neutral),frame,NULL); assert(received==before+1);
    assert(rs3_name("DJI RS3 MINI-test") && !rs3_name("DJI RS3-test") && !rs3_name("other"));
    /* Missing scan-response name cannot hide a saved peer. A different Mini
     * must not replace it, and unnamed first-time devices remain ineligible. */
    const uint8_t saved_peer[6]={1,2,3,4,5,6}, other_peer[6]={1,2,3,4,5,7};
    assert(rs3_candidate(true,saved_peer,saved_peer,NULL));
    assert(rs3_candidate(true,saved_peer,saved_peer,""));
    assert(!rs3_candidate(true,saved_peer,other_peer,"DJI RS3 MINI-test"));
    assert(!rs3_candidate(false,NULL,saved_peer,NULL));
    assert(rs3_candidate(false,NULL,other_peer,"DJI RS3 MINI-test"));
    assert(!rs3_candidate(true,NULL,saved_peer,"DJI RS3 MINI-test"));
    assert(!rs3_candidate(false,NULL,NULL,"DJI RS3 MINI-test"));

    gimbal_control_t s={0}; gimbal_tuning_t cfg={.span=120,.invert_y=true};
    gimbal_input_t in={.connected=true,.epoch=1,.report_ms=1000,.x=127};
    assert(gimbal_control_step(&s,&cfg,&in,true,1000).action==GIMBAL_STOP);
    in.report_ms=1020; assert(gimbal_control_step(&s,&cfg,&in,true,1020).action==GIMBAL_NONE && !s.armed);
    in.x=0; in.report_ms=1040; gimbal_control_step(&s,&cfg,&in,true,1040); assert(s.armed);
    in.x=127; in.y=-128; in.report_ms=1200;
    gimbal_output_t out=gimbal_control_step(&s,&cfg,&in,true,1200);
    assert(out.action==GIMBAL_MOVE && out.pan==120 && out.tilt==120);
    in.report_ms=1220; assert(gimbal_control_step(&s,&cfg,&in,true,1220).action==GIMBAL_NONE);
    in.x=in.y=13; in.report_ms=1240;
    assert(gimbal_control_step(&s,&cfg,&in,true,1240).action==GIMBAL_STOP);
    in.x=in.y=0; in.l3=true; in.report_ms=1260;
    assert(gimbal_control_step(&s,&cfg,&in,true,1260).action==GIMBAL_CENTER);
    in.x=127; in.report_ms=1280; assert(gimbal_control_step(&s,&cfg,&in,true,1280).action==GIMBAL_NONE);
    in.l3=false; in.report_ms=1300; assert(gimbal_control_step(&s,&cfg,&in,true,1300).action==GIMBAL_STOP);
    in.report_ms=1500; assert(gimbal_control_step(&s,&cfg,&in,true,1500).action==GIMBAL_MOVE);
    assert(gimbal_control_step(&s,&cfg,&in,true,1700).action==GIMBAL_STOP && !s.armed);
    in.connected=false; assert(gimbal_control_step(&s,&cfg,&in,true,1720).action==GIMBAL_NONE);
    in.connected=true; in.epoch=2; in.report_ms=1740;
    assert(gimbal_control_step(&s,&cfg,&in,true,1740).action==GIMBAL_STOP && !s.armed);
    assert(gimbal_control_step(&s,&cfg,&in,false,1760).action==GIMBAL_NONE && !s.linked);
    /* Across timer wrap, fresh reports remain valid and 200ms expiry still stops. */
    s=(gimbal_control_t){0}; in=(gimbal_input_t){.connected=true,.epoch=3,.report_ms=UINT32_MAX-20};
    gimbal_control_step(&s,&cfg,&in,true,UINT32_MAX-20);
    in.report_ms=10; gimbal_control_step(&s,&cfg,&in,true,10); assert(s.armed);
    in.x=127; in.report_ms=200; assert(gimbal_control_step(&s,&cfg,&in,true,200).action==GIMBAL_MOVE);
    assert(gimbal_control_step(&s,&cfg,&in,true,400).action==GIMBAL_STOP);
    /* Quadratic curve is monotone and signed, calibrated center stays neutral. */
    int previous=0;
    for (int x=14;x<=127;++x) {
        s=(gimbal_control_t){.linked=true,.armed=true,.epoch=3}; in.x=(int8_t)x; in.report_ms=1000;
        out=gimbal_control_step(&s,&cfg,&in,true,1000); assert(out.pan>=previous); previous=out.pan;
        s.sent=false; in.x=(int8_t)-x; assert(gimbal_control_step(&s,&cfg,&in,true,1000).pan==-out.pan);
    }
    cfg.offset_x=8; cfg.offset_y=-5; in.x=8; in.y=-5;
    s=(gimbal_control_t){.linked=true,.armed=true,.epoch=3};
    out=gimbal_control_step(&s,&cfg,&in,true,1000); assert(out.action==GIMBAL_STOP && !out.pan && !out.tilt);
    /* A stuck L3 does not extend the recenter deadline. Fresh reports continue. */
    cfg.offset_x=cfg.offset_y=0; in.x=in.y=0; in.l3=true; in.report_ms=1200;
    assert(gimbal_control_step(&s,&cfg,&in,true,1200).action==GIMBAL_CENTER);
    in.report_ms=6200; assert(gimbal_control_step(&s,&cfg,&in,true,6200).action==GIMBAL_STOP);
    /* Tilt adjustment must leave pan unchanged, preserve deadzone/inversion,
     * and clamp independently to the protocol's deflection bounds. */
    cfg=(gimbal_tuning_t){.span=120,.tilt_span=240,.invert_y=true};
    in=(gimbal_input_t){.connected=true,.epoch=3,.report_ms=7000,.x=127,.y=-127};
    s=(gimbal_control_t){.linked=true,.armed=true,.epoch=3};
    out=gimbal_control_step(&s,&cfg,&in,true,7000);
    assert(out.action==GIMBAL_MOVE && out.pan==120 && out.tilt==240);
    s.sent=false; in.x=-127; in.y=127;
    out=gimbal_control_step(&s,&cfg,&in,true,7000);
    assert(out.pan==-120 && out.tilt==-240);
    s.sent=false; in.x=in.y=13;
    out=gimbal_control_step(&s,&cfg,&in,true,7000);
    assert(out.action==GIMBAL_STOP && !out.pan && !out.tilt);
    cfg.invert_y=false; cfg.tilt_span=1000; s.sent=false; in.x=in.y=127;
    out=gimbal_control_step(&s,&cfg,&in,true,7000);
    assert(out.pan==120 && out.tilt==400);
    cfg.tilt_span=0; s.sent=false;
    out=gimbal_control_step(&s,&cfg,&in,true,7000);
    assert(out.pan==120 && out.tilt==120);
    return 0;
}
