#pragma once
// Existing wire values; names do not change encoding or validation.
#define PTPIP_PORT 15740
#define PTPIP_PROTOCOL_VERSION 0x00010000u
#define PTPIP_DATA_PHASE_NONE_OR_IN 1u
#define PTPIP_DATA_PHASE_OUT 2u
typedef enum {
    PTPIP_INIT_COMMAND_REQUEST = 1, PTPIP_INIT_COMMAND_ACK = 2,
    PTPIP_INIT_EVENT_REQUEST = 3, PTPIP_INIT_EVENT_ACK = 4,
    PTPIP_INIT_FAIL = 5, PTPIP_OPERATION_REQUEST = 6,
    PTPIP_OPERATION_RESPONSE = 7, PTPIP_EVENT = 8,
    PTPIP_START_DATA = 9, PTPIP_DATA = 10, PTPIP_END_DATA = 12,
    PTPIP_PROBE_REQUEST = 13, PTPIP_PROBE_RESPONSE = 14,
} ptpip_packet_type_t;
#define PTP_OC_GET_DEVICE_INFO 0x1001
#define PTP_OC_OPEN_SESSION 0x1002
#define PTP_OC_CLOSE_SESSION 0x1003
#define PTP_OC_GET_OBJECT_INFO 0x1008
#define PTP_OC_GET_OBJECT 0x1009
#define PTP_RC_OK 0x2001
#define PTP_TYPE_INT16 3
#define PTP_TYPE_UINT16 4
#define PTP_TYPE_UINT32 6

#define PTP_RC_ACCESS_DENIED 0x200f
